"""empty message

Revision ID: 65b3f67d882c
Revises: 91b69ccd4ed1
Create Date: 2022-07-10 16:14:36.231512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b3f67d882c'
down_revision = '91b69ccd4ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'age')
    # ### end Alembic commands ###
