""" DB settings """
DB_TYPE = "mysql"
DB_DRIVER = "pymysql"
DB_USERNAME = "root"
DB_PASSWORD = "root"
DB_HOST = "localhost"
DB_PORT = "3306"
DB_NAME = "flask_demo"

#DB_URL = "sqlite:///demo.db"
DB_URL = f"{DB_TYPE}+{DB_DRIVER}://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"